extern const GeoLayout sign_video_data_geo[];
extern u8 sign_video_data_metal_i8_i8[];
extern u8 sign_video_data_fence_ci4_ci4[];
extern u8 sign_video_data_fence_ci4_pal_rgba16[];
extern Vtx sign_video_data_sign_video_data_mesh_layer_1_vtx_cull[8];
extern Vtx sign_video_data_sign_video_data_mesh_layer_1_vtx_0[64];
extern Vtx sign_video_data_sign_video_data_mesh_layer_1_vtx_1[44];
extern Vtx sign_video_data_sign_video_data_mesh_layer_1_vtx_2[263];
extern Vtx sign_video_data_sign_video_data_mesh_layer_1_vtx_3[12];
extern Vtx sign_video_data_sign_video_data_mesh_layer_4_vtx_cull[8];
extern Vtx sign_video_data_sign_video_data_mesh_layer_4_vtx_0[16];
extern Gfx sign_video_data_sign_video_data_mesh_layer_1_begin[];
extern Gfx sign_video_data_sign_video_data_mesh_layer_1_end[];
extern Gfx sign_video_data_sign_video_data_mesh_layer_4[];
