extern const GeoLayout sign_cheezepin_geo[];
extern u8 sign_cheezepin_metal_i8_i8[];
extern u8 sign_cheezepin_fence_ci4_ci4[];
extern u8 sign_cheezepin_fence_ci4_pal_rgba16[];
extern u8 sign_cheezepin_suecheezepin_rgba16[];
extern Vtx sign_cheezepin_sign_cheezepin_mesh_layer_1_vtx_cull[8];
extern Vtx sign_cheezepin_sign_cheezepin_mesh_layer_1_vtx_0[44];
extern Vtx sign_cheezepin_sign_cheezepin_mesh_layer_1_vtx_1[121];
extern Vtx sign_cheezepin_sign_cheezepin_mesh_layer_1_vtx_2[12];
extern Vtx sign_cheezepin_sign_cheezepin_mesh_layer_1_vtx_3[64];
extern Vtx sign_cheezepin_sign_cheezepin_mesh_layer_4_vtx_cull[8];
extern Vtx sign_cheezepin_sign_cheezepin_mesh_layer_4_vtx_0[16];
extern Gfx sign_cheezepin_sign_cheezepin_mesh_layer_1[];
extern Gfx sign_cheezepin_sign_cheezepin_mesh_layer_4[];
