#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "sun/geo.inc.c"
#include "moon/geo.inc.c"
#include "electrical_pole/geo.inc.c"
#include "bush/geo.inc.c"
#include "pokey/geo.inc.c"
#include "sign_amogus/geo.inc.c"
#include "sign_cheezepin/geo.inc.c"
#include "sign_farm/geo.inc.c"
#include "sign_spoon/geo.inc.c"
#include "sign_joel/geo.inc.c"
#include "sign_simpleflips/geo.inc.c"
#include "sign_ass_impact/geo.inc.c"
#include "sign_mvc/geo.inc.c"
#include "sign_rovert/geo.inc.c"
#include "sign_comit/geo.inc.c"
#include "sign_mushroom/geo.inc.c"
#include "sign_hackern64/geo.inc.c"
#include "sign_synergy/geo.inc.c"
#include "sign_mvh/geo.inc.c"
#include "gas_station/geo.inc.c"
#include "koopa_with_shell_custom/geo.inc.c"