#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "sun/geo.inc.c"
#include "moon/geo.inc.c"
#include "electrical_pole/geo.inc.c"
#include "bush/geo.inc.c"
#include "pokey/geo.inc.c"
#include "gas_station/geo.inc.c"
#include "koopa_with_shell_custom/geo.inc.c"
#include "pokey_body_custom/geo.inc.c"
#include "pokey_head_custom_mesh/geo.inc.c"
#include "goomba_custom_mesh/geo.inc.c"
#include "klepto/geo.inc.c"
#include "ufo_visual/geo.inc.c"
#include "desert_house/geo.inc.c"
#include "desert_house_rgb/geo.inc.c"
#include "sign_normal/geo.inc.c"
#include "sign_video/geo.inc.c"