extern const GeoLayout sign_predator_geo[];
extern u8 sign_predator_predator_ci4[];
extern u8 sign_predator_predator_pal_rgba16[];
extern Vtx sign_predator_sign_predator_mesh_layer_1_vtx_cull[8];
extern Vtx sign_predator_sign_predator_mesh_layer_1_vtx_0[44];
extern Vtx sign_predator_sign_predator_mesh_layer_1_vtx_1[262];
extern Vtx sign_predator_sign_predator_mesh_layer_1_vtx_2[12];
extern Vtx sign_predator_sign_predator_mesh_layer_1_vtx_3[200];
extern Vtx sign_predator_sign_predator_mesh_layer_4_vtx_cull[8];
extern Vtx sign_predator_sign_predator_mesh_layer_4_vtx_0[16];
extern Gfx sign_predator_sign_predator_mesh_layer_1[];
extern Gfx sign_predator_sign_predator_mesh_layer_4[];
