extern const GeoLayout sign_joel_geo[];
extern u8 sign_joel_joel_rgba16[];
extern Vtx sign_joel_sign_joel_mesh_layer_1_vtx_cull[8];
extern Vtx sign_joel_sign_joel_mesh_layer_1_vtx_0[44];
extern Vtx sign_joel_sign_joel_mesh_layer_1_vtx_1[263];
extern Vtx sign_joel_sign_joel_mesh_layer_1_vtx_2[12];
extern Vtx sign_joel_sign_joel_mesh_layer_1_vtx_3[64];
extern Vtx sign_joel_sign_joel_mesh_layer_4_vtx_cull[8];
extern Vtx sign_joel_sign_joel_mesh_layer_4_vtx_0[16];
extern Gfx sign_joel_sign_joel_mesh_layer_1[];
extern Gfx sign_joel_sign_joel_mesh_layer_4[];
