extern const GeoLayout vegas_ending_area_1_geo[];
extern const GeoLayout vegas_ending_area_1[];
extern const Collision vegas_ending_area_1_collision[];
extern const MacroObject vegas_ending_area_1_macro_objs[];
extern u8 vegas_ending_dl_vegas_topdown_rgba16_rgba16[];
extern u8 vegas_ending_dl_road_ci4_ci4[];
extern u8 vegas_ending_dl_road_ci4_pal_rgba16[];
extern u8 vegas_ending_dl_orange_floor_ci4_ci4[];
extern u8 vegas_ending_dl_orange_floor_ci4_pal_rgba16[];
extern u8 vegas_ending_dl_grass_ci4__ci4[];
extern u8 vegas_ending_dl_grass_ci4__pal_rgba16[];
extern u8 vegas_ending_dl_vegas_sign_rgba16_rgba16[];
extern u8 vegas_ending_dl_delano_mask_i8[];
extern u8 vegas_ending_dl_delano_rgba16[];
extern u8 vegas_ending_dl_building1_ci4[];
extern u8 vegas_ending_dl_building1_pal_rgba16[];
extern Vtx vegas_ending_dl_ending_mesh_layer_1_vtx_cull[8];
extern Vtx vegas_ending_dl_ending_mesh_layer_1_vtx_0[204];
extern Gfx vegas_ending_dl_ending_mesh_layer_1_tri_0[];
extern Vtx vegas_ending_dl_ending_mesh_layer_1_vtx_1[199];
extern Gfx vegas_ending_dl_ending_mesh_layer_1_tri_1[];
extern Vtx vegas_ending_dl_ending_mesh_layer_1_vtx_2[276];
extern Gfx vegas_ending_dl_ending_mesh_layer_1_tri_2[];
extern Vtx vegas_ending_dl_ending_mesh_layer_1_vtx_3[99];
extern Gfx vegas_ending_dl_ending_mesh_layer_1_tri_3[];
extern Vtx vegas_ending_dl_ending_mesh_layer_1_vtx_4[230];
extern Gfx vegas_ending_dl_ending_mesh_layer_1_tri_4[];
extern Vtx vegas_ending_dl_ending_mesh_layer_1_vtx_5[132];
extern Gfx vegas_ending_dl_ending_mesh_layer_1_tri_5[];
extern Vtx vegas_ending_dl_ending_mesh_layer_4_vtx_cull[8];
extern Vtx vegas_ending_dl_ending_mesh_layer_4_vtx_0[158];
extern Gfx vegas_ending_dl_ending_mesh_layer_4_tri_0[];
extern Gfx mat_vegas_ending_dl_f3dlite_material_layer1[];
extern Gfx mat_revert_vegas_ending_dl_f3dlite_material_layer1[];
extern Gfx mat_vegas_ending_dl_road_layer1[];
extern Gfx mat_revert_vegas_ending_dl_road_layer1[];
extern Gfx mat_vegas_ending_dl_orange_floor_layer1[];
extern Gfx mat_revert_vegas_ending_dl_orange_floor_layer1[];
extern Gfx mat_vegas_ending_dl_grass_layer1[];
extern Gfx mat_revert_vegas_ending_dl_grass_layer1[];
extern Gfx mat_vegas_ending_dl_welcome_to_vegas_sign_layer4[];
extern Gfx mat_revert_vegas_ending_dl_welcome_to_vegas_sign_layer4[];
extern Gfx mat_vegas_ending_dl_hotel_layer1[];
extern Gfx mat_revert_vegas_ending_dl_hotel_layer1[];
extern Gfx mat_vegas_ending_dl_concrete_layer1[];
extern Gfx mat_revert_vegas_ending_dl_concrete_layer1[];
extern Gfx vegas_ending_dl_ending_mesh_layer_1[];
extern Gfx vegas_ending_dl_ending_mesh_layer_4[];
