extern const GeoLayout desert_area_1_geo[];
extern const GeoLayout desert_dl_0room1_geo[];
extern const GeoLayout desert_dl_0room2_geo[];
extern const GeoLayout desert_area_1[];
extern const Collision desert_area_1_collision[];
extern const u8 desert_area_1_collision_rooms[];
extern const MacroObject desert_area_1_macro_objs[];
extern u8 desert_dl_sand_ci4[];
extern u8 desert_dl_sand_x_dirt_flashbang_ci4_pal_rgba16[];
extern u8 desert_dl_dirt_flashbang_ci4_ci4[];
extern u8 desert_dl_road_ci4_ci4[];
extern u8 desert_dl_road_ci4_pal_rgba16[];
extern u8 desert_dl_dirt_ci4_ci4[];
extern u8 desert_dl_dirt_ci4_pal_rgba16[];
extern u8 desert_dl_wooden_floor_ci4[];
extern u8 desert_dl_wooden_floor_pal_rgba16[];
extern u8 desert_dl_ceiling3_ia8[];
extern u8 desert_dl_marble_wall_i8[];
extern u8 desert_dl_shelf_vertical_rgba16[];
extern u8 desert_dl_shelf_horizontal_rgba16[];
extern u8 desert_dl_marble_i8[];
extern u8 desert_dl_fridge_rgba16[];
extern u8 desert_dl_fridge_side_rgba16[];
extern Vtx desert_dl_desert_mesh_layer_1_vtx_cull[8];
extern Vtx desert_dl_desert_mesh_layer_1_vtx_0[417];
extern Gfx desert_dl_desert_mesh_layer_1_tri_0[];
extern Vtx desert_dl_desert_mesh_layer_1_vtx_1[50];
extern Gfx desert_dl_desert_mesh_layer_1_tri_1[];
extern Vtx desert_dl_desert_mesh_layer_1_vtx_2[294];
extern Gfx desert_dl_desert_mesh_layer_1_tri_2[];
extern Vtx desert_dl_store_interior_mesh_layer_1_vtx_cull[8];
extern Vtx desert_dl_store_interior_mesh_layer_1_vtx_0[58];
extern Gfx desert_dl_store_interior_mesh_layer_1_tri_0[];
extern Vtx desert_dl_store_interior_mesh_layer_1_vtx_1[69];
extern Gfx desert_dl_store_interior_mesh_layer_1_tri_1[];
extern Vtx desert_dl_store_interior_mesh_layer_1_vtx_2[30];
extern Gfx desert_dl_store_interior_mesh_layer_1_tri_2[];
extern Vtx desert_dl_store_interior_mesh_layer_1_vtx_3[24];
extern Gfx desert_dl_store_interior_mesh_layer_1_tri_3[];
extern Vtx desert_dl_store_interior_mesh_layer_1_vtx_4[24];
extern Gfx desert_dl_store_interior_mesh_layer_1_tri_4[];
extern Vtx desert_dl_store_interior_mesh_layer_1_vtx_5[8];
extern Gfx desert_dl_store_interior_mesh_layer_1_tri_5[];
extern Vtx desert_dl_store_interior_mesh_layer_1_vtx_6[8];
extern Gfx desert_dl_store_interior_mesh_layer_1_tri_6[];
extern Vtx desert_dl_store_interior_mesh_layer_1_vtx_7[32];
extern Gfx desert_dl_store_interior_mesh_layer_1_tri_7[];
extern Vtx desert_dl_store_interior_mesh_layer_0_vtx_cull[8];
extern Vtx desert_dl_store_interior_mesh_layer_0_vtx_0[12];
extern Gfx desert_dl_store_interior_mesh_layer_0_tri_0[];
extern Gfx mat_desert_dl_sand_layer1[];
extern Gfx mat_revert_desert_dl_sand_layer1[];
extern Gfx mat_desert_dl_road_layer1[];
extern Gfx mat_revert_desert_dl_road_layer1[];
extern Gfx mat_desert_dl_dirt_layer1_area1[];
extern Gfx mat_revert_desert_dl_dirt_layer1_area1[];
extern Gfx mat_desert_dl_floor[];
extern Gfx mat_revert_desert_dl_floor[];
extern Gfx mat_desert_dl_ceiling_layer0[];
extern Gfx mat_revert_desert_dl_ceiling_layer0[];
extern Gfx mat_desert_dl_wall_layer1[];
extern Gfx mat_revert_desert_dl_wall_layer1[];
extern Gfx mat_desert_dl_black[];
extern Gfx mat_revert_desert_dl_black[];
extern Gfx mat_desert_dl_shelf_vertical[];
extern Gfx mat_revert_desert_dl_shelf_vertical[];
extern Gfx mat_desert_dl_shelf_horizontal[];
extern Gfx mat_revert_desert_dl_shelf_horizontal[];
extern Gfx mat_desert_dl_marble_counter_layer1[];
extern Gfx mat_revert_desert_dl_marble_counter_layer1[];
extern Gfx mat_desert_dl_fridge[];
extern Gfx mat_revert_desert_dl_fridge[];
extern Gfx mat_desert_dl_fridge_side[];
extern Gfx mat_revert_desert_dl_fridge_side[];
extern Gfx desert_dl_desert_mesh_layer_1[];
extern Gfx desert_dl_store_interior_mesh_layer_1[];
extern Gfx desert_dl_store_interior_mesh_layer_0[];
