extern const GeoLayout desert_area_1_geo[];
extern const GeoLayout desert_area_1[];
extern const Collision desert_area_1_collision[];
extern const MacroObject desert_area_1_macro_objs[];
extern u8 desert_dl_sand_ci4[];
extern u8 desert_dl_sand_x_dirt_flashbang_ci4_pal_rgba16[];
extern u8 desert_dl_dirt_flashbang_ci4_ci4[];
extern u8 desert_dl_road_ci4_ci4[];
extern u8 desert_dl_road_ci4_pal_rgba16[];
extern u8 desert_dl_dirt_ci4_ci4[];
extern u8 desert_dl_dirt_ci4_pal_rgba16[];
extern Vtx desert_dl_desert_mesh_layer_1_vtx_cull[8];
extern Vtx desert_dl_desert_mesh_layer_1_vtx_0[417];
extern Gfx desert_dl_desert_mesh_layer_1_tri_0[];
extern Vtx desert_dl_desert_mesh_layer_1_vtx_1[50];
extern Gfx desert_dl_desert_mesh_layer_1_tri_1[];
extern Vtx desert_dl_desert_mesh_layer_1_vtx_2[294];
extern Gfx desert_dl_desert_mesh_layer_1_tri_2[];
extern Gfx mat_desert_dl_sand_layer1[];
extern Gfx mat_revert_desert_dl_sand_layer1[];
extern Gfx mat_desert_dl_road_layer1[];
extern Gfx mat_revert_desert_dl_road_layer1[];
extern Gfx mat_desert_dl_dirt_layer1_area1[];
extern Gfx mat_revert_desert_dl_dirt_layer1_area1[];
extern Gfx desert_dl_desert_mesh_layer_1[];
