extern const GeoLayout sign_comit_geo[];
extern u8 sign_comit_metal_i8_i8[];
extern u8 sign_comit_fence_ci4_ci4[];
extern u8 sign_comit_fence_ci4_pal_rgba16[];
extern u8 sign_comit_mrcomit_rgba16[];
extern Vtx sign_comit_sign_comit_mesh_layer_1_vtx_cull[8];
extern Vtx sign_comit_sign_comit_mesh_layer_1_vtx_0[44];
extern Vtx sign_comit_sign_comit_mesh_layer_1_vtx_1[263];
extern Vtx sign_comit_sign_comit_mesh_layer_1_vtx_2[12];
extern Vtx sign_comit_sign_comit_mesh_layer_1_vtx_3[64];
extern Vtx sign_comit_sign_comit_mesh_layer_4_vtx_cull[8];
extern Vtx sign_comit_sign_comit_mesh_layer_4_vtx_0[16];
extern Gfx sign_comit_sign_comit_mesh_layer_1[];
extern Gfx sign_comit_sign_comit_mesh_layer_4[];
