extern const GeoLayout sign_video_geo[];
extern u8 sign_video_metal_i8_i8[];
extern u8 sign_video_fence_ci4_ci4[];
extern u8 sign_video_fence_ci4_pal_rgba16[];
extern u8 sign_video_video_rgba16[];
extern Vtx sign_video_sign_video_mesh_layer_1_vtx_cull[8];
extern Vtx sign_video_sign_video_mesh_layer_1_vtx_0[44];
extern Vtx sign_video_sign_video_mesh_layer_1_vtx_1[229];
extern Vtx sign_video_sign_video_mesh_layer_1_vtx_2[12];
extern Vtx sign_video_sign_video_mesh_layer_1_vtx_3[54];
extern Vtx sign_video_sign_video_mesh_layer_4_vtx_cull[8];
extern Vtx sign_video_sign_video_mesh_layer_4_vtx_0[16];
extern Gfx sign_video_sign_video_mesh_layer_1_begin[];
extern Gfx sign_video_sign_video_mesh_layer_1_end[];
extern Gfx sign_video_sign_video_mesh_layer_4[];
